apiVersion: v1
kind: LimitRange
metadata:
  name: limit-resources
spec:
  limits:
  - default:
      cpu: 1
      memory: 100Mi
    defaultRequest:
      cpu: 0.5
      memory: 80Mi
    type: Container
